### PR TITLE
this commit fixes #75

### LINKED ISSUE #75: AttributeError in base.py: "_backend_alias"
I use djangocms-blog and the search-function that comes with it (more or less).

When I set
> HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

I get an AttributeError in aldryn_search/base.py line 37 when I want to add a new blog-post:

> AttributeError: 'PostIndex' object has no attribute '_backend_alias'

A simple solution would be to check if _backend_alias is set and set it to None if its not (or DEFAULT_ALIAS from haystack).
```
from haystack.constants import DEFAULT_ALIAS
...
def prepare(self, obj):
    if not hasattr(self, '_backend_alias'):
        self._backend_alias = DEFAULT_ALIAS # or set to None
        ...
```

Would this be possible to implement in an upcoming version or do you think the error is somewhere completely else?

Here is a part of the traceback I get:
```
  File "/usr/local/lib/python3.6/site-packages/djangocms_blog/models.py", line 255, in save
    super(Post, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/parler/models.py", line 657, in save
    super(TranslatableModelMixin, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 833, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python3.6/site-packages/haystack/signals.py", line 52, in handle_save
    index.update_object(instance, using=using)
  File "/usr/local/lib/python3.6/site-packages/haystack/indexes.py", line 284, in update_object
    backend.update(self, [instance])
  File "/usr/local/lib/python3.6/site-packages/haystack/backends/elasticsearch_backend.py", line 168, in update
    prepped_data = index.full_prepare(obj)
  File "/usr/local/lib/python3.6/site-packages/haystack/indexes.py", line 208, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/usr/local/lib/python3.6/site-packages/aldryn_search/base.py", line 37, in prepare
    current_language = self.get_current_language(using=self._backend_alias, obj=obj)
AttributeError: 'PostIndex' object has no attribute '_backend_alias'
```

### PR DESCRIPTION
**Pull request by carderm**
Fix to work with Haystack >= 2.6 and Elasticsearch 2.x

### CODE REVIEW

**Comment by nathan-long** [comment]
832408a works for me.  Were there further issues?  It doesn't look like the build failures were related to this change.

**Comment by vinitkumar** [comment]
Can we please get this merged?

**Comment by marksweb** [comment]
@czpython Can this fix get merged?

I'm just setting up a new project & opted for `django-haystack 2.8.1` so I'm getting that backend grief that this fixes.

**Comment by marksweb** [comment]
@carderm @nlong1 @maj0rr @vinitkumar 
What are you guys doing about this?

Django needs to be at a minimum of 1.11 these days but support for that only comes in a version of `django-haystack` which doesn't work with `aldryn-search`.

What a nightmare.

**Comment by maj0rr** [comment]
Hey @marksweb,
I referenced the fork with the merged fix from:
https://github.com/jdgoettsch/aldryn-search

Requirements:
git+https://github.com/jdgoettsch/aldryn-search@d9720a33ee6251d29e2ec86014af4eb998403f45#egg=aldryn-search

Hope this will help you!

**Comment by marksweb** [comment]
Thanks @maj0rr, I thought that'd be the best solution 👍

**Comment by nicholasjuncos** [comment]
Have to fix this. Either merge this PR or rewrite to work. and push. Just spent hours trying to get this fixed and ended up using @maj0rr repo instead (thank you for saving my life maj0rr)

**Comment by carderm** [comment]
> Have to fix this. Either merge this PR or rewrite to work. and push. Just spent hours trying to get this fixed and ended up using @maj0rr repo instead (thank you for saving my life maj0rr)

Agreed! Given this pull request has no conflicts and is over a year old I've given up on it happening and am just using this branch to add in other useful fixes.  :)
